version: "3.9"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: howiti_app
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        restart: always
        environment:
            - ENV=development
