version: "3.9"
services:
    fastapi_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: howiti_app_container
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        environment:
            - ENV=development
